export const methodsEnum = {
    'SINGLE_LINKAGE': 0,
    'COMPLETE_LINKAGE': 1,
    'AVERAGE_LINKAGE':2 ,
    'EUCLIDIAN_DISTANCE': 0,
    'MANHATTAN_DISTANCE': 1,
    'MAX_DISTANCE': 2,
    'PRINT_VECTOR_VALUE_PRECISION': 2,
    'KMEANS_MAX_ITERATIONS': 10,
    'FCMEANS_MAX_ITERATIONS': 3,
}
